In [3]:
import sqlite3                                 
import pandas as pd                             
 
con = sqlite3.connect('../data/raw/airtel.db')  
 
def q(sql):                                     
    return pd.read_sql(sql, con)

In [4]:
q("""SELECT * FROM circles;""")

    circle_id           circle_name region
0           1                 Delhi  North
1           2                Punjab  North
2           3               Haryana  North
3           4      Himachal Pradesh  North
4           5       Jammu & Kashmir  North
5           6             Rajasthan  North
6           7  Uttar Pradesh (East)  North
7           8  Uttar Pradesh (West)  North
8           9                Mumbai   West
9          10           Maharashtra   West
10         11               Gujarat   West
11         12        Madhya Pradesh   West
12         13        Andhra Pradesh  South
13         14             Karnataka  South
14         15            Tamil Nadu  South
15         16                Kerala  South
16         17               Kolkata   East
17         18           West Bengal   East
18         19                 Bihar   East
19         20                Odisha   East
20         21                 Assam   East
21         22            North East   East

In [7]:
q("""
SELECT count(*)AS total_count,
 count(DISTINCT circle_id) AS distinct_count
 FROM circles;
""")

   total_count  distinct_count
0           22              22

In [10]:
q("""SELECT count(*)
    FROM circles c
    JOIN customers cu
    ON c.circle_id = cu.circle_id
    """)

   count(*)
0     22000

In [11]:
q("""SELECT c.customer_id,c.connection_type,
       (SELECT COUNT(*) FROM recharges r
       where r.customer_id = c.customer_id)
       AS payments
FROM customers c
WHERE NOT EXISTS (SELECT 1 FROM usage_daily u
                  where u.customer_id
                  =c.customer_id);""")

   customer_id connection_type  payments
0          266         Prepaid         1
1        10684         Prepaid        29
2        13508         Prepaid         8
3        19111         Prepaid        39